-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdKTKEnsZUz4LRvEu
jABhbYzIV4iHIiT/zZrVyF4akYmgCgYIKoZIzj0DAQehRANCAARWiuVMDuWsr/NQ
umBPEBf/234d9Uwc1eqEbh3nsoWxIv1DJTHofu1rzvsb/aic3IiBU+8XCNzG6lqn
YXfDJx0K
-----END PRIVATE KEY-----